trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker image
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: 'DockerRegistryConnection'  # 🔁 Your Docker Registry Service Connection
        repository: 'pythonapp'
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: KubernetesManifest@1
      displayName: Deploy to AKS
      inputs:
        action: deploy
        kubernetesServiceConnection: 'AKSServiceConnection'  # 🔁 Your AKS Service Connection
        namespace: default
        manifests: |
          k8s/deployment.yaml
