trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pythonapp'

steps:
- task: Docker@2
  displayName: Build and Push Docker image to ACR
  inputs:
    containerRegistry: 'myacrServiceConnection'  # replace with your Docker Registry service connection name
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: Kubernetes@1
  displayName: Deploy to AKS
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'AzureContainerRegistryConnection'  # your ARM connection
    azureResourceGroup: 'myDevOpsRG'
    kubernetesCluster: 'myAKSCluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      deployment.yml
      service.yml
