trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pythonapp'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker image to ACR'
  inputs:
    containerRegistry: 'AzureContainerRegistryConnection'   # ✅ Azure RM service connection name
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    echo "Docker Image pushed to ACR as $(imageName):$(Build.BuildId)"
  displayName: 'Log Image Push Info'
